[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.6.0",
]

[tool.pytest.ini_options]
markers = [
    "fb_regular: marks regular tests for FeatureBased functions",
    "fb_opt: marks optimizer tests for FeatureBased functions",
    "clustered_mode: marks tests which are supported only by functions that can work in clustered mode",
]

build-backend = "setuptools.build_meta"